"""Local executive cockpit and coaching contracts for E40."""

from .cockpit import (
    build_cockpit,
    render_cockpit_html,
    render_cockpit_json,
    write_cockpit,
)
from .coaching import build_strategy_plan, route_coaching
from .diagnostic import build_diagnostic
from .guidance import build_honest_guidance
from .persistence import (
    PersistenceError,
    load_execution_state,
    save_execution_state,
    save_state,
)
from .models import (
    CockpitArtifact,
    CockpitCard,
    CoachingRequest,
    CoachingRoute,
    DECISIONS,
    CompanyProfile,
    DiagnosticAnswer,
    DecisionAssessment,
    EvidenceItem,
    ExecutiveDiagnostic,
    ExecutiveCockpit,
    OnboardingQuestion,
    OnboardingResult,
    ProfileAnswer,
    ProfileField,
    PainDrillDown,
    KeyCapability,
    OPSPAccountability,
    OPSPCell,
    OPSPColumn,
    OPSPRow,
    StrategyAnswer,
    StrategyPlan,
    ExecutionState,
    ExecutionTask,
    Goal,
    GuidanceRequest,
    HonestGuidance,
    Priority,
    SessionContinuity,
    StateReceipt,
)
from .onboarding import build_company_profile

__all__ = [
    "DECISIONS",
    "CockpitArtifact",
    "CockpitCard",
    "CoachingRequest",
    "CoachingRoute",
    "ExecutionState",
    "ExecutionTask",
    "CompanyProfile",
    "DiagnosticAnswer",
    "DecisionAssessment",
    "EvidenceItem",
    "ExecutiveDiagnostic",
    "ExecutiveCockpit",
    "Goal",
    "GuidanceRequest",
    "HonestGuidance",
    "OnboardingQuestion",
    "OnboardingResult",
    "ProfileAnswer",
    "ProfileField",
    "Priority",
    "SessionContinuity",
    "StateReceipt",
    "PainDrillDown",
    "KeyCapability",
    "OPSPAccountability",
    "OPSPCell",
    "OPSPColumn",
    "OPSPRow",
    "StrategyAnswer",
    "StrategyPlan",
    "build_cockpit",
    "build_company_profile",
    "build_diagnostic",
    "build_honest_guidance",
    "build_strategy_plan",
    "render_cockpit_html",
    "render_cockpit_json",
    "write_cockpit",
    "route_coaching",
    "PersistenceError",
    "load_execution_state",
    "save_execution_state",
    "save_state",
]
