"""Pure Markdown renderer for session summaries."""


def format_summary(summary: dict) -> str:
    """Render a structured session summary as Markdown."""
    decision = (summary.get("decision_focus") or "").capitalize()
    lines = [
        "## Session Summary",
        "",
        f"**Date:** {summary.get('date', '')}",
        f"**Duration:** {summary.get('duration_minutes', 0)} minutes",
        f"**Decision Focus:** {decision}",
    ]

    worksheets = summary.get("worksheets_completed") or []
    if worksheets:
        lines.extend(["", "### What We Worked On", "", f"- Worksheets: {', '.join(worksheets)}"])

    tasks_created = summary.get("tasks_created") or []
    tasks_completed = summary.get("tasks_completed") or []
    if tasks_created or tasks_completed:
        lines.extend(["", "### Tasks", ""])
        if tasks_created:
            lines.append(f"**Created ({len(tasks_created)}):**")
            lines.extend(f"- {task}" for task in tasks_created)
        if tasks_completed:
            if tasks_created:
                lines.append("")
            lines.append(f"**Completed ({len(tasks_completed)}):**")
            lines.extend(f"- {task}" for task in tasks_completed)

    notes = summary.get("notes") or []
    if notes:
        lines.extend(["", "### Key Points", ""])
        lines.extend(f"- {note}" for note in notes)

    lines.extend(
        [
            "",
            "---",
            f"*Summary auto-generated by ScaleUp Coach — {summary.get('date', '')}*",
            "",
        ]
    )
    return "\n".join(lines)
