#!/bin/bash
# Configure the project-local RaiSE MCP server for Codex without touching user state.
set -euo pipefail

# Preserve a test/installer-provided command prefix while retaining the basic
# utilities needed to create a project-local configuration.
PATH="${PATH}:/usr/bin:/bin"

project_root="${1:-}"

if [[ -z "$project_root" || ! -d "$project_root" ]]; then
    echo "Uso: $0 <raiz-del-proyecto>" >&2
    exit 2
fi

if ! pipeline_command="$(command -v rai-mcp-pipeline)"; then
    echo "Aviso: rai-mcp-pipeline no está disponible; se omite la configuración MCP de Codex." >&2
    exit 0
fi

project_root="$(cd "$project_root" && pwd)"
config_directory="$project_root/.codex"
config_path="$config_directory/config.toml"

if [[ -e "$config_path" ]]; then
    echo "La configuración existente de Codex se conserva: $config_path"
    exit 0
fi

toml_escape() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '%s' "$value"
}

escaped_command="$(toml_escape "$pipeline_command")"
escaped_root="$(toml_escape "$project_root")"

umask 077
mkdir -p "$config_directory"
printf '%s\n' \
    '# Generated by scripts/configure_codex_mcp.sh. Keep this project-local.' \
    '[mcp_servers.rai-workspace]' \
    "command = \"$escaped_command\"" \
    "args = [\"--project\", \"$escaped_root\"]" \
    "env = { RAISE_PROJECT_ROOT = \"$escaped_root\" }" \
    > "$config_path"

echo "Configurado rai-workspace MCP para Codex: $config_path"
