"""coaching.summary.formatter — pure markdown renderer.

No I/O. Accepts structured summary dict, returns markdown string.
"""
from __future__ import annotations


def format_summary(summary: dict) -> str:
    """Render a structured summary dict as a markdown section.

    Args:
        summary: Dict produced by engine.build_summary().

    Returns:
        Markdown string starting with '## Session Summary'.
    """
    lines: list[str] = []

    # ── Header ───────────────────────────────────────────────────────────────
    lines.append("## Session Summary")
    lines.append("")
    lines.append(f"**Date:** {summary['date']}")
    lines.append(f"**Duration:** {summary['duration_minutes']} minutes")
    decision = (summary["decision_focus"] or "").capitalize()
    lines.append(f"**Decision Focus:** {decision}")

    # ── What We Worked On (worksheets) ───────────────────────────────────────
    worksheets = summary.get("worksheets_completed") or []
    if worksheets:
        lines.append("")
        lines.append("### What We Worked On")
        lines.append("")
        lines.append(f"- Worksheets: {', '.join(worksheets)}")

    # ── Tasks ─────────────────────────────────────────────────────────────────
    tasks_created = summary.get("tasks_created") or []
    tasks_completed = summary.get("tasks_completed") or []
    if tasks_created or tasks_completed:
        lines.append("")
        lines.append("### Tasks")
        lines.append("")
        if tasks_created:
            lines.append(f"**Created ({len(tasks_created)}):**")
            for task in tasks_created:
                lines.append(f"- {task}")
        if tasks_completed:
            lines.append("")
            lines.append(f"**Completed ({len(tasks_completed)}):**")
            for task in tasks_completed:
                lines.append(f"- {task}")

    # ── Key Points (notes) ───────────────────────────────────────────────────
    notes = summary.get("notes") or []
    if notes:
        lines.append("")
        lines.append("### Key Points")
        lines.append("")
        for note in notes:
            lines.append(f"- {note}")

    # ── Footer ────────────────────────────────────────────────────────────────
    lines.append("")
    lines.append("---")
    lines.append(f"*Summary auto-generated by ScaleUp Coach — {summary['date']}*")
    lines.append("")

    return "\n".join(lines)
