"""Installer-machine workspace contracts for the local Escala runtime."""

from .authority import (
    WorkspaceAuthorityError,
    WorkspaceConfig,
    WorkspaceReceipt,
    init_authoritative_db,
    render_workspace_receipt_json,
    render_workspace_receipt_markdown,
    validate_workspace,
)
from .ingestion import (
    FieldCandidate,
    FormatCapability,
    HeaderCandidate,
    IngestionResult,
    SourceIdentity,
    SourceIngestionError,
    SourceProfile,
    SourceQuestion,
    SourceRegistry,
    TableProfile,
    build_source_identity,
    profile_source,
    render_ingestion_receipt_json,
    render_ingestion_receipt_markdown,
)

__all__ = [
    "WorkspaceAuthorityError",
    "WorkspaceConfig",
    "WorkspaceReceipt",
    "init_authoritative_db",
    "render_workspace_receipt_json",
    "render_workspace_receipt_markdown",
    "validate_workspace",
    "FormatCapability",
    "HeaderCandidate",
    "FieldCandidate",
    "TableProfile",
    "SourceProfile",
    "SourceQuestion",
    "IngestionResult",
    "SourceIdentity",
    "SourceIngestionError",
    "SourceRegistry",
    "build_source_identity",
    "profile_source",
    "render_ingestion_receipt_json",
    "render_ingestion_receipt_markdown",
]
